### ISSUE TITLE
Error in matching data across 2 excel workbooks 

### ISSUE THREAD

**Issue by sam-garate** [sam-garate/Automation#1]
Attached is the code, which matches sheet name, then row value, then column headers & sub headers across 2 excel files, & then pastes the value from 1 file to the other.

The code works fine till the second last line, where its copy-pasting the correct data into most of the cells. However, the last 2 lines sometimes don't paste the correct data. 

[The data in both files is structured in such a way that every other column has headers/sub-headers, so copying the data from 1 cell next shouldn't cause matching problem.]

File A- Parent workbook (from where data has to be copied)
File B- Child workbook (where data has to be pasted after matching sheet name, row & column headings)

[A.xlsx](https://github.com/sam-garate/Automation/files/4308234/A.xlsx)
[B.xlsx](https://github.com/sam-garate/Automation/files/4308235/B.xlsx)

**Comment by WK-GiHu** [comment]
@sam-garate 

Notify me using: @WK-GiHu

Reviewing your code i didn't get the logic?
1. In `B.xlsx` there is, e.g a `2020` Column, but in `A.xlsx` there is no `2020` Column
2. Your shown [`Sample desired Output`](https://i.stack.imgur.com/dihtQ.png) has other `Subq` Letters and only 3 questions but without any values?

**Comment by sam-garate** [comment]
The objective is to be able to draw values from a particular sheet, then question, sub question (the code measures the range of each table in both A.xlsx & B.xlsx so that it searches only within those sub questions) and category (column headers) from A to B. 
B is an empty template where the numbers will get pasted. 
Eg- I want to draw values from Banner 1 of A.xlsx, from question- 'How big is market share?' for subquestion E, for Millennials (column header), for a particular year (column sub-header). 
So the code matches the sheet name, then question, then sub-question and finally the column headers to paste the value in the empty spaces in B.xlsx. 

1. If you check both sheets, there is a 2020 column in 1 of them. 
2. It doesn't need to match all questions and sub-questions, only the ones which are needed/mentioned in B.xlsx.

**Comment by WK-GiHu** [comment]
@sam-garate 

You problem is a simple `whitespace`:

Change the following:
https://github.com/sam-garate/Automation/blob/dc5b3bed4ec35e013cf7a7207f1506d9e4902709/Excel%20Automation-Final%20code.py#L103
```
               subq_i = i.cell(row=rowsb, column=1).value
               if subq_i is not None:
                   subq_i = subq_i.strip()
                                
               if subq == subq_i:
```

or

Remove the `whitespace` from ***A.xlsx Banner 2.Row 11.Column A***

**Comment by sam-garate** [comment]
@WK-GiHu 

[F.xlsx](https://github.com/sam-garate/Automation/files/4313499/F.xlsx)

Attached is the desired output. The numbers are getting populated correctly (i.e.-columns E, G, I etc). The columns next to them (F,H,J) are not getting populated correctly (if you look at F.xlsx, the highlighted cells have incorrect value (or no value) compared to A.xlsx.

The problem is in this line- (line 111)
temp.cell(row=rows2,column=cols1+1).value=i.cell(row=rowsb,column=colsa+1).value

**Comment by WK-GiHu** [comment]
@WK-GiHu 

>The columns next to them (F,H,J) are not getting populated correctly 

You need `step=2` for this `range(2,c_count)` as you are doing `colsa+1`
https://github.com/sam-garate/Automation/blob/dc5b3bed4ec35e013cf7a7207f1506d9e4902709/Excel%20Automation-Final%20code.py#L107
change to:
```
for colsa in range(2, c_count, 2):
```
Read up on: [Python » Documentation  - `range(start, stop[, step])`](https://docs.python.org/3/library/stdtypes.html#range)

**Comment by sam-garate** [comment]
@WK-GiHu
Thank you so much! 
My code is working perfectly now. 
Really appreciate the help!
